### ISSUE TITLE
做业务时用到的插件

### ISSUE THREAD

**Issue by IOriens** [IOriens/ioriens.github.io#15]
着急赶进度的项目都是硬怼，vue、react 都没有上

### 词云
[echarts-wordcloud](https://github.com/ecomfe/echarts-wordcloud)

![image](https://user-images.githubusercontent.com/8137136/38170916-cf6ff5f8-35c1-11e8-9c20-99e4e53aafc9.png)

## 分页
[simplePagination](http://flaviusmatis.github.io/simplePagination.js/)
![image](https://user-images.githubusercontent.com/8137136/38170838-f36fa602-35c0-11e8-837b-5dffaba82960.png)

## Loading
[shCircleLoader](https://jquery.sunhater.com/shCircleLoader/demo)
![image](https://user-images.githubusercontent.com/8137136/38170883-7be1b1ba-35c1-11e8-8bc0-db35a4554ebf.png)

**Comment by IOriens** [comment]
## Snippets
###   取整求千分位
```js
function toThousands (num) {
  if (num == null || num == '暂无数据' || num == '') return num
  var num = (parseInt(num) || 0).toString(), result = ''
  while (num.length > 3) {
    result = ',' + num.slice(-3) + result
    num = num.slice(0, num.length - 3)
  }
  if (num) {
    result = num + result
  }
  return result
}
```

**Comment by IOriens** [comment]
# 其它需求
## 「∙」「•」「・」「●」
[「∙」「•」「・」「●」，一个小点难倒了众多银行](http://daily.zhihu.com/story/2375993)

**Comment by IOriens** [comment]
# CSS 技巧
### 手动加下划线
```css
txt::after {
    content: "";
    width: 100%;
    position: absolute;
    left: 0;
    bottom: 10px;
    border-width: 0 0 4px;
    border-style: solid;
}
```
